name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: android-actions/setup-android@v3
        with:
          packages: 'platforms;android-32'
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b

      - name: Install deps
        run: cargo install cargo-apk

        # Create folder without content to make the build succeed
      - run: mkdir -p deps/android_openxr/arm64-v8a

      - name: Build client
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        working-directory: ./alvr/client_openxr
        run: cargo xtask build-client

      - name: upload it
        uses: actions/upload-artifact@v4.6.1
        with:
          path: ./alvr/client_openxr/target/*.apk
